/// Route names (spec §12). Generated from the screen catalogue.
abstract final class AppRoutes {
  static const splash = '/'; // 01
  static const intro1Welcome = '/intro/1'; // 02
  static const intro2NeverAlone = '/intro/2'; // 03
  static const intro3EveryDay = '/intro/3'; // 04
  static const intro4TrainingNotTherapy = '/intro/4'; // 05
  static const setup1YourName = '/setup/name'; // 06
  static const setup2MeditationReminder = '/setup/time'; // 07
  static const setup3Reminder = '/setup/permission'; // 08
  static const howDoYouWantToStart = '/start'; // 09
  static const purchaseStates = '/purchase/status'; // 11
  static const trialStarted = '/welcome'; // 12
  static const saveYourProgressOptional = '/account/save'; // 13
  static const membershipPaywall = '/membership'; // 14
  static const restorePurchase = '/restore'; // 15
  static const saveYourProgressFreeUser = '/account/save-free'; // 16
  static const signUpWithEmail = '/account/email'; // 17
  static const logIn = '/login'; // 18
  static const forgotPassword = '/login/forgot'; // 19
  static const checkYourEmail = '/login/check'; // 20
  static const todayMember = '/today'; // 22
  static const motdRoom = '/motd'; // 23
  static const todayFree = '/today-free'; // 24
  static const worldMapWorldVibration = '/world'; // 25
  static const dailyMessage = '/message/:date'; // 26
  static const exploreArchive = '/message/archive'; // 27
  static const notifications = '/notifications'; // 28
  static const sosHowCanIHelp = '/sos'; // 30
  static const library = '/library'; // 31
  static const themePage = '/theme/:id'; // 32
  static const search = '/search'; // 34
  static const allPrograms = '/programs'; // 35
  static const programDetail = '/program/:id'; // 36
  static const teacherBio = '/teacher/:id'; // 37
  static const myMeditations = '/recipes'; // 38
  static const buildYourOwn = '/byo'; // 39
  static const buildYourOwnAdvanced = '/byo/advanced'; // 40
  static const sessionDetail = '/session/:id'; // 41
  static const playerPresenceRing = '/player'; // 42
  static const videoPlayer = '/player/video'; // 43
  static const freePlayer = '/player/free'; // 44
  static const meditationCompletePayoff = '/complete'; // 45
  static const shareYourMeditation = '/share'; // 46
  static const sessionDedications = '/dedications/:sessionId'; // 48
  static const silenceRoomSetup = '/silence'; // 50
  static const silenceRoomMeditating = '/silence/run'; // 51
  static const together = '/together'; // 52
  static const groupMeditationLobby = '/lobby'; // 53
  static const you = '/you'; // 54
  static const yourProgress = '/progress'; // 55
  static const editProfile = '/profile/edit'; // 56
  static const reminders = '/reminders'; // 57
  static const downloads = '/downloads'; // 58
  static const privacyData = '/privacy'; // 59
  static const helpAbout = '/help'; // 60
  // Rows 9–11 (no route column in §12)
  static const manageMembership = '/membership/manage'; // 61
  static const trialEnding = '/membership/trial-ending'; // 62 (also sheet)
  static const billingIssue = '/membership/billing'; // 63
  static const membershipEnded = '/membership/ended'; // 64
  static const offline = '/offline'; // 65
  static const updateRequired = '/update'; // 68
  static const challenges = '/soon/challenges'; // 69
  static const gratitude = '/soon/gratitude'; // 70
  static const breathwork = '/soon/breathwork'; // 71
  static const breathPattern = '/soon/breath-pattern'; // 72
  static const milestones = '/soon/milestones'; // 73
  static const intent = '/setup/intent'; // 74 (features.intent)
  // not drawn: set a new password after the reset link, email links, maintenance, deep link not found
  static const pushPreview = '/push-preview'; // 29
  static const resetPassword = '/login/reset';
  static const authLink = '/auth/link';
  static const maintenance = '/maintenance';
  static const notFound = '/not-found';
}
