import 'package:get/get.dart';
import '../../features/system/views/placeholder_page.dart';
import '../../features/account/views/account_pages.dart';
import '../../features/membership/views/membership_pages.dart';
import '../../features/onboarding/views/intro_pages.dart';
import '../../features/today/views/today_pages.dart';
import '../../features/onboarding/views/setup_pages.dart';
import '../../features/onboarding/views/splash_page.dart';
import '../../features/onboarding/views/start_page.dart';
import 'app_routes.dart';

/// Every route has a page from P0; each phase swaps its placeholders for the real screen (spec §14).
abstract final class AppPages {
  static final pages = <GetPage<dynamic>>[
    GetPage(name: AppRoutes.splash, page: () => const SplashPage()),
    GetPage(name: AppRoutes.intro1Welcome, page: () => const IntroPage(1)),
    GetPage(name: AppRoutes.intro2NeverAlone, page: () => const IntroPage(2)),
    GetPage(name: AppRoutes.intro3EveryDay, page: () => const IntroPage(3)),
    GetPage(name: AppRoutes.intro4TrainingNotTherapy, page: () => const IntroPage(4)),
    GetPage(name: AppRoutes.setup1YourName, page: () => const NamePage()),
    GetPage(name: AppRoutes.setup2MeditationReminder, page: () => const TimePage()),
    GetPage(name: AppRoutes.setup3Reminder, page: () => const ReminderPermissionPage()),
    GetPage(name: AppRoutes.howDoYouWantToStart, page: () => const StartPage()),
    GetPage(name: AppRoutes.purchaseStates, page: () => const PurchaseStatusPage()),
    GetPage(name: AppRoutes.trialStarted, page: () => const WelcomePage()),
    GetPage(name: AppRoutes.saveYourProgressOptional, page: () => const SaveProgressPage(free: false)),
    GetPage(name: AppRoutes.membershipPaywall, page: () => const PaywallPage()),
    GetPage(name: AppRoutes.restorePurchase, page: () => const RestorePage()),
    GetPage(name: AppRoutes.saveYourProgressFreeUser, page: () => const SaveProgressPage(free: true)),
    GetPage(name: AppRoutes.signUpWithEmail, page: () => const EmailSignUpPage()),
    GetPage(name: AppRoutes.logIn, page: () => const LoginPage()),
    GetPage(name: AppRoutes.forgotPassword, page: () => const ForgotPasswordPage()),
    GetPage(name: AppRoutes.checkYourEmail, page: () => const CheckEmailPage()),
    GetPage(name: AppRoutes.todayMember, page: () => const TodayPage()),
    GetPage(name: AppRoutes.motdRoom, page: () => const PlaceholderPage('motdRoom')),
    GetPage(name: AppRoutes.todayFree, page: () => const TodayFreePage()),
    GetPage(name: AppRoutes.worldMapWorldVibration, page: () => const PlaceholderPage('worldMapWorldVibration')),
    GetPage(name: AppRoutes.dailyMessage, page: () => const PlaceholderPage('dailyMessage')),
    GetPage(name: AppRoutes.exploreArchive, page: () => const PlaceholderPage('exploreArchive')),
    GetPage(name: AppRoutes.notifications, page: () => const PlaceholderPage('notifications')),
    GetPage(name: AppRoutes.sosHowCanIHelp, page: () => const PlaceholderPage('sosHowCanIHelp')),
    GetPage(name: AppRoutes.library, page: () => const PlaceholderPage('library')),
    GetPage(name: AppRoutes.themePage, page: () => const PlaceholderPage('themePage')),
    GetPage(name: AppRoutes.search, page: () => const PlaceholderPage('search')),
    GetPage(name: AppRoutes.allPrograms, page: () => const PlaceholderPage('allPrograms')),
    GetPage(name: AppRoutes.programDetail, page: () => const PlaceholderPage('programDetail')),
    GetPage(name: AppRoutes.teacherBio, page: () => const PlaceholderPage('teacherBio')),
    GetPage(name: AppRoutes.myMeditations, page: () => const PlaceholderPage('myMeditations')),
    GetPage(name: AppRoutes.buildYourOwn, page: () => const PlaceholderPage('buildYourOwn')),
    GetPage(name: AppRoutes.buildYourOwnAdvanced, page: () => const PlaceholderPage('buildYourOwnAdvanced')),
    GetPage(name: AppRoutes.sessionDetail, page: () => const PlaceholderPage('sessionDetail')),
    GetPage(name: AppRoutes.playerPresenceRing, page: () => const PlaceholderPage('playerPresenceRing')),
    GetPage(name: AppRoutes.videoPlayer, page: () => const PlaceholderPage('videoPlayer')),
    GetPage(name: AppRoutes.freePlayer, page: () => const PlaceholderPage('freePlayer')),
    GetPage(name: AppRoutes.meditationCompletePayoff, page: () => const PlaceholderPage('meditationCompletePayoff')),
    GetPage(name: AppRoutes.shareYourMeditation, page: () => const PlaceholderPage('shareYourMeditation')),
    GetPage(name: AppRoutes.sessionDedications, page: () => const PlaceholderPage('sessionDedications')),
    GetPage(name: AppRoutes.silenceRoomSetup, page: () => const PlaceholderPage('silenceRoomSetup')),
    GetPage(name: AppRoutes.silenceRoomMeditating, page: () => const PlaceholderPage('silenceRoomMeditating')),
    GetPage(name: AppRoutes.together, page: () => const PlaceholderPage('together')),
    GetPage(name: AppRoutes.groupMeditationLobby, page: () => const PlaceholderPage('groupMeditationLobby')),
    GetPage(name: AppRoutes.you, page: () => const PlaceholderPage('you')),
    GetPage(name: AppRoutes.yourProgress, page: () => const PlaceholderPage('yourProgress')),
    GetPage(name: AppRoutes.editProfile, page: () => const PlaceholderPage('editProfile')),
    GetPage(name: AppRoutes.reminders, page: () => const PlaceholderPage('reminders')),
    GetPage(name: AppRoutes.downloads, page: () => const PlaceholderPage('downloads')),
    GetPage(name: AppRoutes.privacyData, page: () => const PlaceholderPage('privacyData')),
    GetPage(name: AppRoutes.helpAbout, page: () => const PlaceholderPage('helpAbout')),
    GetPage(name: AppRoutes.manageMembership, page: () => const ManageMembershipPage()),
    GetPage(name: AppRoutes.trialEnding, page: () => const TrialEndingPage()),
    GetPage(name: AppRoutes.billingIssue, page: () => const BillingIssuePage()),
    GetPage(name: AppRoutes.membershipEnded, page: () => const MembershipEndedPage()),
    GetPage(name: AppRoutes.offline, page: () => const PlaceholderPage('offline')),
    GetPage(name: AppRoutes.updateRequired, page: () => const PlaceholderPage('updateRequired')),
    GetPage(name: AppRoutes.challenges, page: () => const PlaceholderPage('challenges')),
    GetPage(name: AppRoutes.gratitude, page: () => const PlaceholderPage('gratitude')),
    GetPage(name: AppRoutes.breathwork, page: () => const PlaceholderPage('breathwork')),
    GetPage(name: AppRoutes.breathPattern, page: () => const PlaceholderPage('breathPattern')),
    GetPage(name: AppRoutes.milestones, page: () => const PlaceholderPage('milestones')),
    GetPage(name: AppRoutes.intent, page: () => const PlaceholderPage('intent')),
    GetPage(name: AppRoutes.maintenance, page: () => const PlaceholderPage('maintenance')),
    GetPage(name: AppRoutes.notFound, page: () => const PlaceholderPage('notFound')),
    GetPage(name: AppRoutes.resetPassword, page: () => const ResetPasswordPage()),
    GetPage(name: AppRoutes.authLink, page: () => const AuthLinkPage()),
  ];
}
