import 'package:get/get.dart';
import '../../features/system/views/placeholder_page.dart';
import '../../features/onboarding/views/splash_page.dart';
import 'app_routes.dart';

/// Every route has a page from P0; each phase swaps its placeholders for the real screen (spec §14).
abstract final class AppPages {
  static final pages = <GetPage<dynamic>>[
    GetPage(name: AppRoutes.splash, page: () => const SplashPage()),
    GetPage(name: AppRoutes.intro1Welcome, page: () => const PlaceholderPage('intro1Welcome')),
    GetPage(name: AppRoutes.intro2NeverAlone, page: () => const PlaceholderPage('intro2NeverAlone')),
    GetPage(name: AppRoutes.intro3EveryDay, page: () => const PlaceholderPage('intro3EveryDay')),
    GetPage(name: AppRoutes.intro4TrainingNotTherapy, page: () => const PlaceholderPage('intro4TrainingNotTherapy')),
    GetPage(name: AppRoutes.setup1YourName, page: () => const PlaceholderPage('setup1YourName')),
    GetPage(name: AppRoutes.setup2MeditationReminder, page: () => const PlaceholderPage('setup2MeditationReminder')),
    GetPage(name: AppRoutes.setup3Reminder, page: () => const PlaceholderPage('setup3Reminder')),
    GetPage(name: AppRoutes.howDoYouWantToStart, page: () => const PlaceholderPage('howDoYouWantToStart')),
    GetPage(name: AppRoutes.purchaseStates, page: () => const PlaceholderPage('purchaseStates')),
    GetPage(name: AppRoutes.trialStarted, page: () => const PlaceholderPage('trialStarted')),
    GetPage(name: AppRoutes.saveYourProgressOptional, page: () => const PlaceholderPage('saveYourProgressOptional')),
    GetPage(name: AppRoutes.membershipPaywall, page: () => const PlaceholderPage('membershipPaywall')),
    GetPage(name: AppRoutes.restorePurchase, page: () => const PlaceholderPage('restorePurchase')),
    GetPage(name: AppRoutes.saveYourProgressFreeUser, page: () => const PlaceholderPage('saveYourProgressFreeUser')),
    GetPage(name: AppRoutes.signUpWithEmail, page: () => const PlaceholderPage('signUpWithEmail')),
    GetPage(name: AppRoutes.logIn, page: () => const PlaceholderPage('logIn')),
    GetPage(name: AppRoutes.forgotPassword, page: () => const PlaceholderPage('forgotPassword')),
    GetPage(name: AppRoutes.checkYourEmail, page: () => const PlaceholderPage('checkYourEmail')),
    GetPage(name: AppRoutes.todayMember, page: () => const PlaceholderPage('todayMember')),
    GetPage(name: AppRoutes.motdRoom, page: () => const PlaceholderPage('motdRoom')),
    GetPage(name: AppRoutes.todayFree, page: () => const PlaceholderPage('todayFree')),
    GetPage(name: AppRoutes.worldMapWorldVibration, page: () => const PlaceholderPage('worldMapWorldVibration')),
    GetPage(name: AppRoutes.dailyMessage, page: () => const PlaceholderPage('dailyMessage')),
    GetPage(name: AppRoutes.exploreArchive, page: () => const PlaceholderPage('exploreArchive')),
    GetPage(name: AppRoutes.notifications, page: () => const PlaceholderPage('notifications')),
    GetPage(name: AppRoutes.sosHowCanIHelp, page: () => const PlaceholderPage('sosHowCanIHelp')),
    GetPage(name: AppRoutes.library, page: () => const PlaceholderPage('library')),
    GetPage(name: AppRoutes.themePage, page: () => const PlaceholderPage('themePage')),
    GetPage(name: AppRoutes.search, page: () => const PlaceholderPage('search')),
    GetPage(name: AppRoutes.allPrograms, page: () => const PlaceholderPage('allPrograms')),
    GetPage(name: AppRoutes.programDetail, page: () => const PlaceholderPage('programDetail')),
    GetPage(name: AppRoutes.teacherBio, page: () => const PlaceholderPage('teacherBio')),
    GetPage(name: AppRoutes.myMeditations, page: () => const PlaceholderPage('myMeditations')),
    GetPage(name: AppRoutes.buildYourOwn, page: () => const PlaceholderPage('buildYourOwn')),
    GetPage(name: AppRoutes.buildYourOwnAdvanced, page: () => const PlaceholderPage('buildYourOwnAdvanced')),
    GetPage(name: AppRoutes.sessionDetail, page: () => const PlaceholderPage('sessionDetail')),
    GetPage(name: AppRoutes.playerPresenceRing, page: () => const PlaceholderPage('playerPresenceRing')),
    GetPage(name: AppRoutes.videoPlayer, page: () => const PlaceholderPage('videoPlayer')),
    GetPage(name: AppRoutes.freePlayer, page: () => const PlaceholderPage('freePlayer')),
    GetPage(name: AppRoutes.meditationCompletePayoff, page: () => const PlaceholderPage('meditationCompletePayoff')),
    GetPage(name: AppRoutes.shareYourMeditation, page: () => const PlaceholderPage('shareYourMeditation')),
    GetPage(name: AppRoutes.sessionDedications, page: () => const PlaceholderPage('sessionDedications')),
    GetPage(name: AppRoutes.silenceRoomSetup, page: () => const PlaceholderPage('silenceRoomSetup')),
    GetPage(name: AppRoutes.silenceRoomMeditating, page: () => const PlaceholderPage('silenceRoomMeditating')),
    GetPage(name: AppRoutes.together, page: () => const PlaceholderPage('together')),
    GetPage(name: AppRoutes.groupMeditationLobby, page: () => const PlaceholderPage('groupMeditationLobby')),
    GetPage(name: AppRoutes.you, page: () => const PlaceholderPage('you')),
    GetPage(name: AppRoutes.yourProgress, page: () => const PlaceholderPage('yourProgress')),
    GetPage(name: AppRoutes.editProfile, page: () => const PlaceholderPage('editProfile')),
    GetPage(name: AppRoutes.reminders, page: () => const PlaceholderPage('reminders')),
    GetPage(name: AppRoutes.downloads, page: () => const PlaceholderPage('downloads')),
    GetPage(name: AppRoutes.privacyData, page: () => const PlaceholderPage('privacyData')),
    GetPage(name: AppRoutes.helpAbout, page: () => const PlaceholderPage('helpAbout')),
    GetPage(name: AppRoutes.manageMembership, page: () => const PlaceholderPage('manageMembership')),
    GetPage(name: AppRoutes.trialEnding, page: () => const PlaceholderPage('trialEnding')),
    GetPage(name: AppRoutes.billingIssue, page: () => const PlaceholderPage('billingIssue')),
    GetPage(name: AppRoutes.membershipEnded, page: () => const PlaceholderPage('membershipEnded')),
    GetPage(name: AppRoutes.offline, page: () => const PlaceholderPage('offline')),
    GetPage(name: AppRoutes.updateRequired, page: () => const PlaceholderPage('updateRequired')),
    GetPage(name: AppRoutes.challenges, page: () => const PlaceholderPage('challenges')),
    GetPage(name: AppRoutes.gratitude, page: () => const PlaceholderPage('gratitude')),
    GetPage(name: AppRoutes.breathwork, page: () => const PlaceholderPage('breathwork')),
    GetPage(name: AppRoutes.breathPattern, page: () => const PlaceholderPage('breathPattern')),
    GetPage(name: AppRoutes.milestones, page: () => const PlaceholderPage('milestones')),
    GetPage(name: AppRoutes.intent, page: () => const PlaceholderPage('intent')),
    GetPage(name: AppRoutes.maintenance, page: () => const PlaceholderPage('maintenance')),
    GetPage(name: AppRoutes.notFound, page: () => const PlaceholderPage('notFound')),
  ];
}
